### ISSUE TITLE
Verwendung für nicht Voltbasierte Sensoren

### ISSUE THREAD

**Issue by n3roGit** [Pittini/iobroker-Batterienauswertung#1]
Wie verwende ich das Script, wenn ich ausschließlich Sensoren verwende die den Batteriestand als
a: 0-100% 
b: true/false 
übermitteln?

**Comment by Pittini** [comment]
> Wie verwende ich das Script, wenn ich ausschließlich Sensoren verwende die den Batteriestand als
> a: 0-100%
> b: true/false
> übermitteln?

Ganz normal wie beschrieben. Egal was die Sensoren melden, da is ne Batterie drin und deren Nennspannung gibst Du der Funktion mit und legst auch ganz normal ne Limitspannung fest wenn die Vorgabe nicht passen sollte. Bei Sensoren die nur true/false liefern is die Auswertefunktionalität natürlich eingeschränkt, erkannt werden sie automatisch anhand des Datentyps des Datenpunktes.
Das gilt auch für Sensoren mit % Werten, leider gibt es unterschiedliche "Definitionen" was die % nun eigentlich bedeuten. Deswegen gibt es Zeile 18 in den Einstellungen, da legst Du fest wie die % gewertet werden, siehe auch Erklärung bei "Info" in der Anleitung. 

PS: Für reine Fragen die keine Bugmeldungen oder Erweiterungswünsche sind, kannste auch gern den [Forumthread](https://forum.iobroker.net/topic/31676/vorlage-generische-batteriestands%C3%BCberwachung-vis-ausgabe) nutzen:
