### ISSUE TITLE
Was muss eingetragen werden bei: %, LOW, usw, Aquara Sensore

### ISSUE THREAD

**Issue by Lordcybertracker** [Pittini/iobroker-Batterienauswertung#11]
Hallo,
Was muss ich angeben bei den Aquara Sensoren oder wen nur % Zahlen da sind?
Oder wenn wie bei den 433 die nur angeben Batterie LOW?
Danke

**Comment by Pittini** [comment]
Installationsanweisung .1

**Comment by Lordcybertracker** [comment]
Das hab ich gesehen. Ich aber Sensoren die nur ein Low Senden.
Oder eben nur Prozent drin haben.

**Comment by Pittini** [comment]
> Das hab ich gesehen. Ich aber Sensoren die nur ein Low Senden.
> Oder eben nur Prozent drin haben.

Ja und? Kaufst für die Batterien mit Spannung lowbat? Oder Batterien mit Spannung %? Du sollst die Batteriespannung angeben wie beschrieben, den Rest erkennt das Skript.

**Comment by Lordcybertracker** [comment]
Die 433 senden aber die Volt Zahl nicht Sondern nur wenn leer sind.
Aber Ok Damit kann ich leben das ich die eben in einem anderen Script ausgeben lasse.
Danke

**Comment by Pittini** [comment]
Da hier nix mehr kommt, nehm ich an dasses klappt und mach zu.
