### ISSUE TITLE
Fehlermeldungne im Log

### ISSUE THREAD

**Issue by Lordcybertracker** [Pittini/iobroker-Batterienauswertung#12]
Hallo,
ich hab folgenden Fehlermeldungen im Log:

javascript.0 | 2021-03-17 18:47:36.236 | error | (16946)     at processImmediate (internal/timers.js:463:21)
-- | -- | -- | --
javascript.0 | 2021-03-17 18:47:36.236 | error | (16946)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1971:38)
javascript.0 | 2021-03-17 18:47:36.236 | error | (16946)     at Object.<anonymous> (script.js.common.BattUeberwachung:106:13)
javascript.0 | 2021-03-17 18:47:36.236 | error | (16946)     at main (script.js.common.BattUeberwachung:235:5)
javascript.0 | 2021-03-17 18:47:36.236 | error | (16946)     at CheckDeadBatt (script.js.common.BattUeberwachung:351:13)
javascript.0 | 2021-03-17 18:47:36.235 | error | (16946)     at MakeTable (script.js.common.BattUeberwachung:548:111)
javascript.0 | 2021-03-17 18:47:36.234 | error | (16946) Error in callback: TypeError: Cannot read property 'common' of null
javascript.0 | 2021-03-17 18:47:36.231 | warn | (16946) Object "javascript.0.TTN.HSN-Node.Node-02" does not exist

Ist das ein Problem oder ist es egal?
es kommt auch immer nur einmal nach dem Instanz neustart.
Ok, kommt auch so. Obwohl die Warnung sich verändert also unterschiedlich anzeigt.

**Comment by Lordcybertracker** [comment]
OK hab den Fehler. Ich kann bei Selbst erstellten Datenpunkten den Raum nicht zuweisen.
Ist es da auch möglich?
![grafik](https://user-images.githubusercontent.com/52379353/111544830-61ffa780-8775-11eb-8f58-d68f79443401.png)

**Comment by Pittini** [comment]
Weil das nur n Ordner aber kein echter Channel ist. Mach halt nen Channel draus:

setObject("mqtt.0.Wetterstation.Case", { type: 'channel', common: { name: "Der gewünschte Name des channels" }, native: {} });

**Comment by Pittini** [comment]
Da hier nix mehr kommt, nehm ich an dasses geklappt hat und mach zu.
