### ISSUE TITLE
Batteriespannung wird als "NaNV" angezeigt

### ISSUE THREAD

**Issue by stony2k** [Pittini/iobroker-Batterienauswertung#14]
Ich habe noch HomeMatic Classic Aktoren im Einsatz, die im Datenpunkt keine Spannung ausgeben. Stattdessen gibt es nur den Datenpunkt LOWBAT und LOWBAT_ALARM. Der Anleitung entsprechend habe ich dem Datenpunkt LOWBAT (3x AA Batterien) die Funktion BatterieSpannung_45 für 4,5 V zugewiesen. Die Funktion DeadCheck habe ich dem Datenpunkt STATE zugewiesen.

Nun ist der Fall eingetreten, dass die Battie vom Aktor leer ist. LOWBAT ist auf true gewechselt, auch die HomeMatic Zentrale gibt eine Meldung aus. Die Batterieauswertung ist allerdings weiterhin grün und zeigt bei "U Ist" NaNV, "%bat" NaN% und "%live" NaN% an. Gemäß der Anleitung sollte man ja selbst bei Aktoren ohne definitive Spannung im Datenpunkt die Funktion mit der korrekten Batterispannung zuweisen.

Mache ich etwas falsch? Sind Screenshots oder Logs gewünscht?

Edit: JavaScript Adapter und danach das Script neugestartet, jetzt funktioniert die Anzeige und das Gerät wird als leer gemeldet. Aber evtl. könnten wir dem Bug ja trotzdem auf die Schliche kommen?

Edit 2: Nach dem Wechsel der Batterie werden die Wert (bis auf U Limit) in der HTML Auswertung wieder mit "NaNV" angezeigt.

**Comment by Pittini** [comment]
Bitte mal ein Log, und nen Screenshot wo ich im aufgeklappteten Objektbaum die Zuweisung seh.

**Comment by stony2k** [comment]
Vor dem Aktivieren des Loggings:
<img width="788" alt="1" src="https://user-images.githubusercontent.com/16526471/116132930-656c4400-a6ce-11eb-80ce-7859c8ff70c3.PNG">
<img width="785" alt="2" src="https://user-images.githubusercontent.com/16526471/116132932-6604da80-a6ce-11eb-8e1a-cc6cc91451f8.PNG">
<img width="391" alt="3" src="https://user-images.githubusercontent.com/16526471/116132933-669d7100-a6ce-11eb-99da-8294735588d5.PNG">

Habe im Script logging aktiviert, das Script wurde neu geladen, jetzt wird der Fensterkontakt korrekt als leer angezeigt. Glaube die Log bringt dir doch nichts, wenn es jetzt richtig angezeigt wird? Gefühlt muss ich den JS Adapter, oder ggf. eher das Script periodisch neu starten, damit alles korrekt ausgelesen wird?

[iobroker.txt](https://github.com/Pittini/iobroker-Batterienauswertung/files/6379367/iobroker.txt)

**Comment by Pittini** [comment]
Ja, wenn geht bringt Log wenig, letzter Stand ging aber ja nicht. Wenns durch den neustart jetzt passt ist das seltsam und würde auf nen Triggerfehler hindeuten. Hab grad noch mal drübergeschaut, ich seh da nix komisches im Skript, und vorallem bei meinen HM lowbat Geräten klappts ja auch. Das einzige was ich mir noch vorstellen kann, ist "Küche" mit "ü", wir leben zwar 2021 aber tatsächlich gibts immer noch und wieder mal Probleme mit deutschen Sonderzeichen.
Das andere ist, lowbat zu nehmen und nochmal lowbat für den 2ten Check, das macht nich soo viel Sinn. Der 2te Deadcheck sollte dann z.B. auf State liegen, also leg mal beides in den "1" Zweig.

**Comment by stony2k** [comment]
Ich hatte testweise das zweite lowbat genommen, in der Hoffnung, dass dein Script dann besser funktioniert. Problem mit den Sonderzeichen macht Sinn, aber wieso funktioniert es nach einem Script Neustart? Es müsste doch entweder mit deutschen Sonderzeichen gehen oder nicht. Und kein "mal gehts und mal nicht" oder? Ich lege den 2. Deadcheck mal auf den State. Wobei Lowbat doch völlig ausreichen müsste. Es war ja vor dem Script Neustart definitiv bereits auf true.

Wie gehen wir nun weiter vor, wie kann ich dich bei der Fehlersuche/-behebung untersützten?

**Comment by Pittini** [comment]
> Wie gehen wir nun weiter vor, wie kann ich dich bei der Fehlersuche/-behebung untersützten?

Ein Log posten wenns nicht geht, inkl. Screenshots, genau wie oben.

**Comment by stony2k** [comment]
Problem trat noch einmal auf, aktuell aber nicht mehr. Können wir noch abwarten, bis es wieder auftritt?

**Comment by Pittini** [comment]
Ich mach hier mal dicht, scheint ja zu laufen. Sollte doch nochmal was auftreten kannste ja wieder aufmachen.
