### ISSUE TITLE
Ausfall oder disconnect bei Aqara-Gerät

### ISSUE THREAD

**Issue by Siggi0904** [Pittini/iobroker-Batterienauswertung#15]
Hallo,
bei mir läuft manchmal eine Mail auf mit der Meldung "Ausfall oder disconnect ..."
Das betrifft aber gefühlt nur einen Aqara-Sensor.
Wenn ich dann in die Variablen schauen ist bei der Batterieauswertung alles gut (keine toten Geräte)
und der Sensor selbst ist auch am Leben.

Gibt es eine Möglichkeit die Prüfung zeitlich zu erweitern?
Wo könnte der Fehler bzw. Ausfall herkommen?

Ich habe `DeadIsAfter = 180` und `NotifyDeadDevices = true` gesetzt.
Wenn das Gerät wirklich so lange tot wäre, würde sich Alexa melden, 
da hier ein blockly auf die Erreichbarkeit der Geräte läuft.

Danke für eine mögliche Untersuchung des Skripts und eine Lösungsfindung.

Danke.

**Comment by Pittini** [comment]
Hör ich zum ersten mal. Ohne Logs wär alles nur geraten, also passe ich. Lönnte evtl. nur sein dasses für das Gerät zeitlich "knapp" ist, dann wird gemeldet und ne Minute später aktualisiert das Ding und dann wird das natürlich zurückgesetzt und Du sihst nix mehr. Also mal genau in dem Moment wo die Meldung kommt guggen und das Log kopieren bei eingeschaltetem Logging im Skript.

**Comment by Pittini** [comment]
Geschlossen wegen Inaktivität.
