### ISSUE TITLE
Upgrade auf js-controller 3.3: Warunugen wg fehlendem ack-flag

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [Pittini/iobroker-Batterienauswertung#16]
Nach upgrade auf controller 3.3. Warnungen. Z.B.
`Read-only state "javascript.0.BatterieUeberwachung.DeadDeviceCount" has been written without ack-flag with value "4"`

**Comment by Pittini** [comment]
Fixed with V 1.7.3, please check.

**Comment by Pittini** [comment]
Passt das jetzt oder kommen noch Meldungen?

**Comment by OstfrieseUnterwegs** [comment]
löppt
