### ISSUE TITLE
New strange entries in the log

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Pittini/iobroker-Batterienauswertung#17]
What do we have to do?

javascript.0 | 2021-05-18 06:59:42.376 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.OverviewTable" has been written without ack-flag with value "&lt;table style='width:100%; border: 1px solid black; border-collapse: collapse;'
javascript.0 | 2021-05-18 06:59:42.376 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.DeadDeviceCount" has been written without ack-flag with value "0"
javascript.0 | 2021-05-18 06:58:42.376 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.OverviewTable" has been written without ack-flag with value "&lt;table style='width:100%; border: 1px solid black; border-collapse: collapse;'
javascript.0 | 2021-05-18 06:58:42.376 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.DeadDeviceCount" has been written without ack-flag with value "0"

**Comment by MichaelSchaaf999** [comment]
a lot of messages now...

javascript.0 | 2021-05-21 07:57:44.511 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.OverviewTable" has been written without ack-flag with value "&lt;table style='width:100%; border: 1px solid black; border-collapse: collapse;'
javascript.0 | 2021-05-21 07:57:44.511 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.DeadDeviceCount" has been written without ack-flag with value "2"
javascript.0 | 2021-05-21 07:56:44.511 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.OverviewTable" has been written without ack-flag with value "&lt;table style='width:100%; border: 1px solid black; border-collapse: collapse;'
javascript.0 | 2021-05-21 07:56:44.511 | warn | (10432) Read-only state "javascript.0.BatterieUeberwachung01.DeadDeviceCount" has been written without ack-flag with value "2"

**Comment by Pittini** [comment]
Which Scriptversion you are using?

**Comment by MichaelSchaaf999** [comment]
1.7.0

**Comment by Pittini** [comment]
![2021-05-21 09_32_05-Window](https://user-images.githubusercontent.com/51408942/119099777-89921b00-ba17-11eb-92af-439f25a0aa50.png)

**Comment by MichaelSchaaf999** [comment]
okay, how do I update from 1.7.0 to 1.7.3?
There are probably some changes in the basic setup, so I cannot just copy the new version into the old script.
What do you recommend? Is there some kind of automatic backup available? I assume that no.

**Comment by Pittini** [comment]
There are also changes in Basic setup with Version 1.7.1, so you have to renew your Basic setup settings. But its not so much, make a Screenshot from your old Basic setup, copy the whole new script over the old one, and setup according to the screenshot.

**Comment by MichaelSchaaf999** [comment]
Done, thanks a lot. Will monitor the script and logs.
