### ISSUE TITLE
Gerät wird als dead angezeigt, obwohl LOWBAT false ist

### ISSUE THREAD

**Issue by stony2k** [Pittini/iobroker-Batterienauswertung#18]
Scriptversion 1.7.3
JS Controller 5.1.3

Habe ein sehr komisches Phänomen:
Meine Fernbedienung bietet mir nur den Datenpunkt LOWBAT zur Batterieüberwachung. Daher habe ich auch keinen Deadcheck gesetzt, sondern nur die Batteriespannung_30 (dieser sollte doch am Datenpunkt LOWBAT zur Überwachung ausreichen, oder?)

Dennoch wird das Gerät als dead angezeigt. DAs dürfte doch erst passieren, sobald LOWBAT true ist, zumindest habe ich das so verstanden. Bei den Kanälen 1-4 wurde nichts zugewiesen.

![Screenshot 2021-05-23 083459](https://user-images.githubusercontent.com/16526471/119250644-c38f2880-bba1-11eb-83e3-0a6f98395f37.jpg)

> 2021-05-23 08:28:07.786 -&nbsp;info: javascript.0 (18467) script.js.Überwachung.Batterieauswertung: Device hm-rpc.1.HMPBI4FM01 is possibly dead, searching for second check

> 2021-05-23 08:28:07.787 -&nbsp;info: javascript.0 (18467) script.js.Überwachung.Batterieauswertung: No second checkpoint found for hm-rpc.1.HMPBI4FM01 so its really dead

> 2021-05-23 08:28:07.787 -&nbsp;info: javascript.0 (18467) script.js.Überwachung.Batterieauswertung: Jim...he's dead

![Screenshot 2021-05-23 083414](https://user-images.githubusercontent.com/16526471/119250622-abb7a480-bba1-11eb-8ba7-63e89456698f.jpg)

**Comment by Pittini** [comment]
> Dennoch wird das Gerät als dead angezeigt. DAs dürfte doch erst passieren, sobald LOWBAT true ist, zumindest habe ich das so verstanden.

Dann haste es falsch verstanden. Wenn ein Gerät leer ist, senden einge halt gar nix mehr, auch kein lowbat=true. Der DeadCheck prüft ob der Datenpunkt innerhalb einer gewissen Zeit aktualisiert wurde, wenn nein > tot. Jetzt aktualsieren dummerweise aber einige Geräte diesen Datenpunkt nur alle Schaltjahre mal, deswegen kann man den zusätzlichen DeadCheck auf nen Datenpunkt legen der halt öfters aktualisiert wird. Ergo, soweit alles korrekt am aktuellen Verhalten.

**Comment by stony2k** [comment]
Heißt BatterieSpannung_30 auf dem Datenpunkt LOWBAT funktioniert bei den HomeMatic Geräten nur dann sinnvoll, wenn die CCU den auf true setzt?

Wäre es nicht eine Option die "Zeitprüfung" bei den LOWBAT Datenpunkten auszuschalten? Oder eine Option für HomeMatic Geräte / Nutzer einzubauen? Bei der Fernbedienung kann es  nämlich sein, dass ich sie auch ein paar Tage einfach mal nicht nutze. Deswegen habe ich bisher keinen DeadCheck auf die einzelnen Tastendrücke gelegt.

**Comment by Pittini** [comment]
Statt eines Opt-Out für HM Geräte hab ich jetzt die auto Prüfung entfernt und als Opt-In via DeadCheck Funktion umgesetzt. D.h. überall wo gewünscht MU? nun die DeadCheck Funktion gesetzt werden, wo nicht gewünscht einfach weglassen. Integriert mit V 1.8.0

**Comment by quersumme** [comment]
Hmm, ich habe ein Zigbee-Netzwerk von so 25 Sensoren.  Bisher fande ich es super das ich eine Meldung bekommen habe, wenn sich ein Sensor längere Zeit nicht verbunden hat.
Das kann ja bei ZigBee schnell mal passieren, wenn die Repeater nicht so gut positioniert sind oder nicht erreichbar sind.
Muss ich dann jetzt jedes Gerät in dem Zigbee Netzwerk der DeadCheck Funktion hinzufügen?

**Comment by Pittini** [comment]
Ja. Filtern und zack zack. Ich hab 65 Sensoren und keine 2 Minuten gebraucht.
