### ISSUE TITLE
Tabelle nach Raum sortieren

### ISSUE THREAD

**Issue by bastian1607** [Pittini/iobroker-Batterienauswertung#19]
Ich habe ein Request für ein Enhancement: Ich würde gerne die Tabelle nach einem Raum sortieren können.

**Comment by stony2k** [comment]
Das wäre jetzt zumindest mit der aktuellen Version möglich, sofern du eine Tabelle im JSON Format nutzen möchtest. Wäre das eine Alternative für dich?

**Comment by bastian1607** [comment]
Hallo zusammen,
kaum schaut man einen Tag nicht rein. :-)

Sehr gut, passt für mich perfekt! Danke und Danke @Pittini !

**Comment by stony2k** [comment]
Gerne. Ich nutze Jarvis und da kann man mit einer JSON Tabelle alles nach den eigenen Wünschen formatieren, deswegen habe ich das mit eingebaut und Pittini hat den Pull Request genehmigt :)

**Comment by bastian1607** [comment]
Sehr gut. Ich nutze die Inventwo-Widges, für mich völlig ausreichend.
Jarvis installiere ich mir immer mal regelmäßig, fühle mich da aber am
Anfang überfordert mit und deinstalliere es. :-D Wobei es optisch auch
super aussieht.

Danke dir für den Einbau!



stony2k ***@***.***> schrieb am Di., 7. Dez. 2021, 21:04:

**Comment by stony2k** [comment]
In Jarvis muss man rein kommen, mit der V3 Beta klappt das mittlerweile
sehr gut. Versuch es gerne nochmal, einmal drin lässt es sich nicht mehr
los.

bastian1607 ***@***.***> schrieb am Di., 7. Dez. 2021, 21:13:
