### ISSUE TITLE
MinVoltage passt nicht bei 3V Geräten

### ISSUE THREAD

**Issue by sphings79** [Pittini/iobroker-Batterienauswertung#2]
In den Objekten steht 2.4V als Minimum für die 3V Geräte.
Trotzdem wird mit 2.6V als Minimum ausgewertet.
Die 2.4V aus den Objekten werden ignoriert.

Btw: in Zeile 264 ist ein Rechtscheibfehler MinLinmit -> MinLimit

**Comment by Pittini** [comment]
> Die 2.4V aus den Objekten werden ignoriert.

Bestätigt, da triggert der Trigger nicht, behoben mit V1.5.3

> Btw: in Zeile 264 ist ein Rechtscheibfehler MinLinmit -> MinLimit

Auch bestätigt und mit 1.5.3 korrigiert. Is aber nur der Text des Logs, hatte keinerlei funktionale Auswirkungen.
