### ISSUE TITLE
Datenpunkt LastMessage wird nicht befüllt

### ISSUE THREAD

**Issue by Frank795** [Pittini/iobroker-Batterienauswertung#20]
Wie schon im Forum geschieben wird der Datenpunkt nicht befüllt erst wieder bei neustart des Skipts. 

![vis](https://user-images.githubusercontent.com/53878761/122665435-76ee3b80-d1a7-11eb-809c-3e15c2fc88ae.png)

![Batt DP](https://user-images.githubusercontent.com/53878761/122665437-7a81c280-d1a7-11eb-94a0-cf9b4491aa1a.png)

**Comment by Pittini** [comment]
Naja, is klar, Du hast 0 leere Batts, sobald der Zähler auf 0 geht wird die Lastmessage gelöscht weil ja sonst nach Batteriewechsel immer noch leer drinstehen würde. Is also eher Feature als Bug.

**Comment by Frank795** [comment]
Sollten nicht die "Toten" auch drin stehen ? Wenn ich das Skipt neu starte steht es drin ....

**Comment by Pittini** [comment]
Hmm, lass uns mal was probieren. In Zeile 420ff steht aktuell:



`CheckAllBatterysOk();
 CheckNextLowBatt();
 CheckDeadBatt();
 MakeTable();`

daraus machste mal bitte:

`CheckNextLowBatt();
 CheckDeadBatt();
CheckAllBatterysOk();
 MakeTable();`

Und dann bitte berichten ob das was half.

**Comment by Frank795** [comment]
Ist geändert und DeadIsAfter soweit runter das aktuell keine gemeldet werden. Melde mich. Danke für deinen Support 👍

**Comment by Frank795** [comment]
Das hat leider nicht geholfen, jetzt bleibt das Widget sogar grün.  siehe Bilder ....
![Bat neu](https://user-images.githubusercontent.com/53878761/122669399-6d6fce00-d1bd-11eb-922f-9dde66e74ee8.PNG)
![BatDP neu](https://user-images.githubusercontent.com/53878761/122669405-73fe4580-d1bd-11eb-8ea3-47c58d39e928.PNG)

**Comment by Pittini** [comment]
Ok, dann Kommando zurück, ich schau mal, kann aber bisserl dauern.

**Comment by Frank795** [comment]
Ja kein Problem 👍   Zeigt ja Rot an das was nicht stimmt... ein Klick auf die Liste und Gut :)

**Comment by Pittini** [comment]
Soo, bitte mal 1.7.5 testen, sollte jetzt passen.

**Comment by Frank795** [comment]
Hi, mit der 1.7.5 klappt es noch nicht, teste später oder morgen die 1.8. 

![Bat DPneu](https://user-images.githubusercontent.com/53878761/122805928-fc6a0c80-d2c9-11eb-9cdf-2e40cd23eee3.PNG)
![vis neu](https://user-images.githubusercontent.com/53878761/122805937-fe33d000-d2c9-11eb-8af6-6df031951c50.PNG)

**Comment by Frank795** [comment]
Hi, auch mit der 1.8.0 die selbe "Problematik" 
![DP 1 8 0](https://user-images.githubusercontent.com/53878761/122963727-d5bddb80-d386-11eb-9617-170d5eea9db2.PNG)

**Comment by Pittini** [comment]
Sorry, iwie war da n Kuddelmuddel im Code. Ich hab die gesamte Funktion jetzt neu geschrieben und hoffe mal dasses jetzt klappt, ich hab alle Varianten die mir einfielen durchgetestet und keine Probleme mehr festgestellt. Bitte also die 1.8.1 mal testen.

**Comment by Frank795** [comment]
Super arbeit 👍 🥇 funktioniert. Echt Klassse 
Jetzt noch Sinnfolle DP´s für den Dead Check suchen und einrichten.
