### ISSUE TITLE
Meldungen über Telegram doppelt

### ISSUE THREAD

**Issue by quersumme** [Pittini/iobroker-Batterienauswertung#21]
Ich habe heute die Version 1.7.5 eingerichtet und anhand der tollen Anleitungen war das auch kein großes Problem.

Nach dem Starten des Scriptes kommen direkt die ersten Meldungen reingeflattert:

```
TelegramBot
Ausfall oder disconnect im Esszimmer bei Gerät Thermometer Esszimmer
Ausfall oder disconnect im Finns Zimmer bei Gerät Thermometer Finn
Ausfall oder disconnect im Esszimmer bei Gerät Thermometer Esszimmer<br>Ausfall oder disconnect im Küche bei Gerät Thermometer Küche<br>Ausfall oder disconnect im Finns Zimmer bei Gerät Thermometer Finn<br>Ausfall oder disconnect im Nicht zugewiesen bei Gerät MFKZQ01LM
Ausfall oder disconnect im Nicht zugewiesen bei Gerät MFKZQ01LM
Ausfall oder disconnect im Küche bei Gerät Thermometer Küche
```

Frage: Diese HTML Formatierte Ausgabe kommt nur nach dem ersten Start des Scriptes. Danach nicht mehr. Bekommt man sie dennoch weg?

Nach einer Minute kommt dann noch mal die Meldung der Küche und dann alle 11-20 (??) Minuten...
```
TelegramBot
Ausfall oder disconnect im Küche bei Gerät Thermometer Küche
```
Warum kommt dann nur noch das Gerät aus der Küche? 

Vielen Dank schon mal :)

**Comment by quersumme** [comment]
Dieses` <br>` ist auch bei den Limit Warnungen in Telegram vorhanden:

`Batteriestand unter Limit im Schlafzimmer bei Gerät Thermostat<br>Batteriestand unter Limit im Badezimmer bei Gerät Thermostat<br>Batteriestand unter Limit im Wohnzimmer bei Gerät Thermostat<br>Batteriestand unter Limit im Finns Zimmer bei Gerät Thermostat`

**Comment by Pittini** [comment]
Bitte verwende mal die 1.8.1 Das <br> is html Zeilenumbruch den manchen brauchen/wollen, kannste in Zeile 64 ändern, gibt dann halt u.U. ne lange Textwurst.

**Comment by quersumme** [comment]
Super, danke. Hab in Zeile 64 statt <br> folgendes eingegeben:

let LastMessageSeparator = "\n";
