### ISSUE TITLE
Skript findet kein Device und bringt Fehler bei CheckNextLowBatt

### ISSUE THREAD

**Issue by db1mso** [Pittini/iobroker-Batterienauswertung#27]
Hallo.
Das Skript findet leider kein Device und bleibt vermutlich deswegen bei CheckNextLowBatt hängen.

Log:
<html>
<body>

18:15:25.348 | info | javascript.0 (25371) Start javascript script.js.common.BattUeberwachung
-- | -- | --
18:15:25.362 | info | javascript.0 (25371) script.js.common.BattUeberwachung: starting Batterieüberwachung V.1.8.5
18:15:25.362 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Reaching FillWelcheFunktionVerwenden
18:15:25.363 | info | javascript.0 (25371) script.js.common.BattUeberwachung: registered 0 subscriptions and 0 schedules
18:15:25.406 | info | javascript.0 (25371) script.js.common.BattUeberwachung: CreateStates fertig!
18:15:25.407 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Reaching main()
18:15:25.407 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Reaching init()
18:15:25.408 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Reaching CheckAllBatterys() found 0 Devices
18:15:25.408 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Reaching CheckLastMessage, EmptyBatCount=0 DeadDeviceCount=0
18:15:25.409 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Alle Batterien ok, Lastmessage gelöscht
18:15:25.409 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Reaching CheckAllBatterysOk
18:15:25.409 | info | javascript.0 (25371) script.js.common.BattUeberwachung: Reaching CheckNextLowBatt()
18:15:25.411 | error | javascript.0 (25371) at CheckNextLowBatt (script.js.common.BattUeberwachung:395:91)
18:15:25.411 | error | javascript.0 (25371) at main (script.js.common.BattUeberwachung:265:5)
18:15:25.411 | error | javascript.0 (25371) at Object.<anonymous> (script.js.common.BattUeberwachung:126:13)

</body>
</html>

Setup:
js-controller: v3.3.18 nodejs: v12.22.5  js: v5.2.13
Exakt 1 Homematic Fensterkontakt:
![image](https://user-images.githubusercontent.com/2564478/145254423-849c01a0-da85-48b4-bf12-b0ef89411880.png)
in exakt 1 Funktion:
![image](https://user-images.githubusercontent.com/2564478/145254745-b1b0ef45-f605-4d86-8c2e-72ddd9e53fc5.png)

Die Funktion "DeadCheck" ist zwar angelegt aber ohne Inhalt. Es ändert sich aber auch das Verhalten nicht, wenn ich ein Objekt zuordne.

Auszug aus dem Skript:
![image](https://user-images.githubusercontent.com/2564478/145255318-a7e0c567-3293-425d-8d7f-0a01dd8ca373.png)

THX

**Comment by stony2k** [comment]
> CheckAllBatterys() found 0 Devices

Benenn deine Funktion "Batterie 3V" mal bitte in "BatterieSpannung_30" um. Bei mir findet er 18 Geräte, ich habe testweise die Aufzählung bei mir in "Batterie Spannung 1,5 V" umbenannt (JS Adapter neu gestartet) und zwack wurden 5 Geräte weniger gefunden.

Bitte also genauso wie in Punkt 1 der [Installation](https://github.com/Pittini/iobroker-Batterienauswertung#installation) :)

**Comment by db1mso** [comment]
Vielen Dank für den Tipp. Ich hatte nicht damit gerechnet, dass ein Skript mit dem Namen anstatt der ID arbeitet.
Es wurde jetzt genau 1 Device gefunden.
