### ISSUE TITLE
LowBattery

### ISSUE THREAD

**Issue by Ball-Pic** [Pittini/iobroker-Batterienauswertung#28]
Hallo
Dein script ist wirklich toll
Der großteil meiner Geräte liefern leider keinen Spannungswert, sondern liefern nur ein LowBattery (false/true).
Wie verwende ich den boolean-Wert?

**Comment by Pittini** [comment]
> Wie verwende ich den boolean-Wert?

Erkennt das Skript selber, einfach an die Anleitung halten.
