### ISSUE TITLE
Berechnung / Auswertung 

### ISSUE THREAD

**Issue by LJSven** [Pittini/iobroker-Batterienauswertung#3]
Hi Carlo,
bist du dir sicher, daß die Berechnung bei %-Werten vom deconz Adapter korrekt sind?

Der Sensor mit der ID 23 hat einen Batteriewert von 38%

![Bildschirmfoto 2020-06-16 um 11 58 30](https://user-images.githubusercontent.com/8560588/84760846-e5168600-afc8-11ea-96cf-31f62cc55641.png)

Der Sensor mit der ID 29 hat einen Batteriewert von 98%

![Bildschirmfoto 2020-06-16 um 11 59 02](https://user-images.githubusercontent.com/8560588/84760897-f495cf00-afc8-11ea-83f1-b72bab952886.png)

In der HTML Tabelle wird mir aber angegeben, daß der **Sensor 29 "kritisch"** angezeigt.

![Bildschirmfoto 2020-06-16 um 11 54 38](https://user-images.githubusercontent.com/8560588/84760966-10997080-afc9-11ea-920a-9e6aaa6df3b4.png)

Bei den Sensoren, die 100% haben, wird die Spannung mit 2.4V angegeben, obwohl es 3.0V sein müssten.

**Comment by Pittini** [comment]
Das Thema hat ich gestern erst auf FB, das Problem ist, dass die Datenpunkte der Prozente kein Unit angegeben haben (also % Zeichen), somit erkennt das Skript nicht dasses Prozent sind.
Ich würde bei den betreffenden Sensoren das % im Raw einfach nachtragen. einfach die "Unit" Zeile ins RAW dazusetzen, siehe Bild. Dann sollte 
![Inked2020-06-15 19_27_54-objects - ioBroker_LI](https://user-images.githubusercontent.com/51408942/84768177-16e11a00-afd4-11ea-928f-3243775a75a1.jpg)
klappen.

**Comment by LJSven** [comment]
Hi Carlo,
das war ich gestern auf Facebook - ich habe überall die % als Unit dazu geschrieben, die Berechnung passt aber nicht.

**Comment by Pittini** [comment]
Auf was steht Zeile 20, true oder false? Wenn Du die % nachgetragen hast, warum seh ich dann nix davon auf den Screenshots? Undn komplettes startlog wär hilfreich, dann seh ich evtl. wo es hakt.

**Comment by LJSven** [comment]
Das % steht im RAW ->

![Bildschirmfoto 2020-06-16 um 13 53 25](https://user-images.githubusercontent.com/8560588/84771109-2151e280-afd9-11ea-9650-b2aa94f003e4.png)

Allerdings müsste nach meinem Verständnis die ZEILE 38 - den gleichen Wert aussspucken, wie die %-Zahl im Adapter. Und das macht er nicht - die Zeile 39 gibt den korrekten Wert aus.
![Bildschirmfoto 2020-06-16 um 13 55 33](https://user-images.githubusercontent.com/8560588/84771080-14cd8a00-afd9-11ea-9fde-3221672b60aa.png)

**Comment by Pittini** [comment]
Du hast noch nicht gesagt auf was Zeile 20 eingestellt ist. Hast Du schon versucht die andere Option zu nehmen NACHDEM Du die % nachgetragen hast?

**Comment by LJSven** [comment]
Das sind meine Settings ->

`//Grund Einstellungen
const praefix = "0_userdata.0.BatterieUeberwachung."; //Grundpfad für Script DPs
const logging = false; //Logging aktivieren?
const FunktionBaseName = "BatterieSpannung_"; //Name der Funktion welche für die Batterieüberwachung genutzt wird
const UseTelegram = true; // Sollen Nachrichten via Telegram gesendet werden?
const UseMail = false; // Sollen Nachrichten via Mail gesendet werden?
const UseAlexa = false; // Sollen Nachrichten via Alexa ausgegeben werden?
const AlexaId = ""; // Die Alexa Seriennummer
const UseSay = false; // Sollen Nachrichten via Say ausgegeben werden? Funktion des Authors, sollte bei Anwendern auf false gesetzt werden.
const UseEventLog = false; // Sollen Nachrichten ins Eventlog geschreiben werden? Funktion des Authors, sollte bei Anwendern auf false gesetzt werden.
const UsePopUp = false // Soll PopUp angezeigt werden? Funktion des Authors, sollte bei Anwendern auf false gesetzt werden.
const ProzMeansLive = true; //Zeigen Prozentwerte des Gerätedatenpunktes Batteriekapazität oder restliche Lebensdauer?
let DeadIsAfter = 720; // In Minuten - Zeit nach der ein Gerät als "tot" gewertet wird wenn keine Statusänderung (ts) erfolgte.`

Wenn ich ZEILE 20 auf true stehen habe - kommt folgendes heraus ->

![Bildschirmfoto 2020-06-16 um 17 51 57](https://user-images.githubusercontent.com/8560588/84797429-1bb8c480-affa-11ea-8ce1-dcfba17b2394.png)

Steht ZEILE 20 auf "false" -> kommt diese Auswertung ->

![Bildschirmfoto 2020-06-16 um 17 52 54](https://user-images.githubusercontent.com/8560588/84797539-3ab75680-affa-11ea-89b9-9ecc8b0cf1e8.png)

**Comment by Pittini** [comment]
Jetzt wärs schon toll gewesen wenn die beiden Screenshots vergleichbar gewesen wären, also 2 mal den gleichen Teil der Liste am besten so dass Sensor 23 und 29 zu sehen sind. Und bitte auch die %bat Spalte mal einblenden. Variante true sieht ja überzeugender aus, da würden auch die 38% und 98% passen. Jetzt mal rausfinden warum der gelbe Balken da ist wo er ist.
Und ganz blöde Frage, hast Du den JS Adapter mal neugestartet nachdem Du die % hinzugefügt hast? Wenn nein, bitte mal machen.

**Comment by LJSven** [comment]
Hier mal die beiden Ausschnitte ->

ZEILE 20 - false
![Bildschirmfoto 2020-06-17 um 09 30 45](https://user-images.githubusercontent.com/8560588/84868716-6a5b7280-b07d-11ea-9cf8-a87588152fd1.png)

ZEILE 20 - true
![Bildschirmfoto 2020-06-17 um 09 31 18](https://user-images.githubusercontent.com/8560588/84868742-72b3ad80-b07d-11ea-80e2-c17e6c27ea17.png)

Javascript Instanz wurde neu gestartet - keine Veränderung.

**Comment by Pittini** [comment]
Hab grad nen update (1.6.3) hochgeladen, bitte mal testen.

**Comment by LJSven** [comment]
Sieht gut aus ->

![Bildschirmfoto 2020-06-17 um 20 04 34](https://user-images.githubusercontent.com/8560588/84933206-d79af200-b0d5-11ea-9c62-8d7024b7942f.png)

**Comment by LJSven** [comment]
@Pittini Das Script schickt keine Mail in der neuen Version - obwohl useTelegram auf "true" steht.

`//Grund Einstellungen
const praefix = "0_userdata.0.BatterieUeberwachung."; //Grundpfad für Script DPs
const logging = false; //Logging aktivieren?
const FunktionBaseName = "BatterieSpannung_"; //Name der Funktion welche für die Batterieüberwachung genutzt wird
const UseTelegram = true; // Sollen Nachrichten via Telegram gesendet werden?
const UseMail = false; // Sollen Nachrichten via Mail gesendet werden?
const UseAlexa = false; // Sollen Nachrichten via Alexa ausgegeben werden?
const AlexaId = ""; // Die Alexa Seriennummer
const UseSay = false; // Sollen Nachrichten via Say ausgegeben werden? Funktion des Authors, sollte bei Anwendern auf false gesetzt werden.
const UseEventLog = false; // Sollen Nachrichten ins Eventlog geschreiben werden? Funktion des Authors, sollte bei Anwendern auf false gesetzt werden.
const UsePopUp = false // Soll PopUp angezeigt werden? Funktion des Authors, sollte bei Anwendern auf false gesetzt werden.
const ProzMeansLive = true; //Zeigen Prozentwerte des Gerätedatenpunktes Batteriekapazität oder restliche Lebensdauer?
let DeadIsAfter = 180; // In Minuten - Zeit nach der ein Gerät als "tot" gewertet wird wenn keine Statusänderung (ts) erfolgte.`

![Bildschirmfoto 2020-06-18 um 09 24 11](https://user-images.githubusercontent.com/8560588/84990619-b2de6300-b145-11ea-8881-096469334362.png)

**Comment by Pittini** [comment]
> Das Script schickt keine Mail in der neuen Version - obwohl useTelegram auf "true" steht.

Daran hab ich überhaupt nix geändert, von daher sag ich mal kann das eigentlich nicht sein. Mach mal das Logging an und schau ob er da meldet. Ansonsten bitte Log posten, bitte als Code, nicht wie oben als Wurscht ohne Umbrüche.

**Comment by LJSven** [comment]
Okay, nach Neustart des Scripts bekomme ich die Mail - aber nicht, wenn das Gerät sich "tot" meldet.

**Comment by Pittini** [comment]
> Okay, nach Neustart des Scripts bekomme ich die Mail - aber nicht, wenn das Gerät sich "tot" meldet.

Das war doch auch noch nie anders. Kann ich aber leicht "nachrüsten" wenn Dir das wichtig ist.

**Comment by LJSven** [comment]
Okay, aber würde es nicht sinn machen, daß es eine Meldung gibt, wenn ein Gerät sich verabschiedet?

**Comment by Pittini** [comment]
Sollte jetzt klappen. 1.6.4 grad hochgeladen.
