### ISSUE TITLE
DeadCheck

### ISSUE THREAD

**Issue by HolgerOnGithub** [Pittini/iobroker-Batterienauswertung#30]
Warum ermittelt der DeadCheck den falschen Zustand?
Siehe angehängte Fotos, eigentliche dürfte nur 1 Gerät auf Dead stehen.
Auch ein Neustart des Skript bringt keine Änderung.
Erst nach dem Neustart des gesamten ioBrokers sind vorübergehend diese Werte richtig.
VIS
![DeadCheck2](https://user-images.githubusercontent.com/68544715/149307470-0d0a6808-a25f-428f-a316-30ee6f68e824.JPG)
Objekte
![DeadCheck3](https://user-images.githubusercontent.com/68544715/149307474-24a4e98a-045c-4ddf-8bb5-d63b2a1f3bde.JPG)

**Comment by Pittini** [comment]
Das Skript wertet den Zeitstempel aus, also bitte mal kontrollieren wann die letzte Änderung war. Der Inhalt des Datenpunktes is dem Skript egal.

**Comment by HolgerOnGithub** [comment]
![DeadCheck5](https://user-images.githubusercontent.com/68544715/149316540-2c4eedfa-87fb-4e01-82f9-54c06e13b2c4.JPG)
![DeadCheck4](https://user-images.githubusercontent.com/68544715/149316544-6e3cb51e-6164-4af7-8fc6-e462b7737e63.JPG)

**Comment by HolgerOnGithub** [comment]
kann ich das ändern das DeadCheck den Wert auswertet anstelle des Zeitstempels? Die Temp. Fühler aktualisieren die °C und Batt sowie Batt% eigentlich sehr gut. Beim Button dagegen finde ich kaum ein Datenpunkt der regelmäßig aktualisiert wird (wenn er nicht betätigt wird) Bzw. gibt es eine seperate Zeiteinstellung für den DeadCheck? Oder muss ich
let DeadIsAfter = 360; auf 24h also 1440 hochsetzten? einmal am Tag beim Restart 0:34 aktualisieren sich schon alle Datenpunkte.

**Comment by Pittini** [comment]
> Oder muss ich
> let DeadIsAfter = 360; auf 24h also 1440 hochsetzten?

Genau so.

**Comment by HolgerOnGithub** [comment]
Vielen Dank für die Erklärung
