### ISSUE TITLE
Raumanzeige funktioniert bei Homematic Komponenten nicht, wenn mit dem hm adapter auch die Räume aus der CCU übernommen werden.

### ISSUE THREAD

**Issue by Soc007** [Pittini/iobroker-Batterienauswertung#31]
Habe im iobroker Forum das Thema angesprochen.
Bitte hier für Details reinschauen.

https://forum.iobroker.net/topic/51597/hm-rega-raumzuordnung-von-homematic-ccu-unvollständig/5

**Comment by Pittini** [comment]
Warum nicht einfach die Synchronisierung abschalten? Hab ich bei mir so gemacht weil mich das HM Gedöns auch genervt hat.

**Comment by Soc007** [comment]
Wenn das so einfach geht, dann ist das sicherlich die beste Lösung.
Hatte aber vermutet, wenn ich den sync der Räume ausschalte, beim restart der rega Instanz er mit alle Raumzuordnung wieder löscht.
Ich gehe aber nach deiner Aussage davon aus, dass das nicht so ist und ich "nur" den einmaligen Aufwand habe die Räume zuzuordnen.
