### ISSUE TITLE
Script enthält einen kleinen Fehler

### ISSUE THREAD

**Issue by Soc007** [Pittini/iobroker-Batterienauswertung#32]
Im Script wird in der function ventilateRoom die Werte für humidityThreshold und minHumidity aus den einzelnen Räumen nicht berücksichtigt, sondern ein fester Wert verwendet.

Ich habe es wie folgt angepasst.

function ventilateRoom(relHumidityInside, tempInside, relHumidityOutside, tempOutside,
                       threshold, minHumidity) { // replace
//                       threshold = 2.0, minHumidity = 50.0) {

**Comment by Pittini** [comment]
Ich würde meinen....Du hast Dich verlaufen. Solche Funktionen und Variablen gibts nich in meinem Skript.

**Comment by Soc007** [comment]
Sorry, hast natürlich recht. 
Bin da bei Dir vollkommen falsch gewesen. ;-)
