### ISSUE TITLE
Error 25 bei Installationsversuch

### ISSUE THREAD

**Issue by Matt77CHE** [Pittini/iobroker-Batterienauswertung#33]
wollte den Adapter installieren;
Bin in Beta und mir wurde der Adapter im Iobroker nicht angezeigt, auch nicht bei der Katze - als ich ihn direkt von Github installieren wollte, kam bei der Installation der Error 25 im Log....

**Comment by Rudi-Ment** [comment]
Hi
Ist kein Adapter. 
Ist ein Skript. 
Anleitung ist hier zu finden ...
Ich setze das Skript schon länger ein. Funzt super.

**Comment by Matt77CHE** [comment]
Achso; Sorry - Danke für den Schupser....
