### ISSUE TITLE
Gerätname wird nicht angezeigt..

### ISSUE THREAD

**Issue by cainam1** [Pittini/iobroker-Batterienauswertung#36]
Die Meldungen sind immer mit Gerätename "Information" und nicht der effektive Name. Zb:

"Ausfall oder disconnect im Toilette bei Gerät Information"

**Comment by Pittini** [comment]
Na dann wird vermutlich Deine Struktur nicht passen. Zeig mal nen Screenshot der Objektliste von so nem Gerät.

**Comment by cainam1** [comment]
![image](https://user-images.githubusercontent.com/18394514/178973212-dce2ad9a-0b65-4875-bc4c-58e32e8e8cf1.png)

**Comment by cainam1** [comment]
gerade gesehen dass ich gar nicht die neuste version hab... versuche jetzt mal
