### ISSUE TITLE
Gerät löschen

### ISSUE THREAD

**Issue by totocotonio** [Pittini/iobroker-Batterienauswertung#38]
Hallo, 
ich habe ein Gerät gelöscht und es wird mir trotzdem in der VIS noch angezeigt.

Kannst du mir da helfen?

**Comment by slimline33** [comment]
Hast du dein Skript mal neugestartet?

**Comment by totocotonio** [comment]
ja

**Comment by totocotonio** [comment]
das Gerät steht auch nicht mehr in den Aufzählungen

**Comment by slimline33** [comment]
Und den Javascript Adapter auch mal neu gestartet? Hi und da hängt es dort...

**Comment by totocotonio** [comment]
Ja auch neu gestartet, brachte keinen Erfolg . Gerät ist immer noch da.

**Comment by Pittini** [comment]
Von nix kommt nix, wenn das Skript ein Gerät anzeigt, isses auch noch iwo vorhanden. Meist sinds "Leichen" in den Aufzählungen bisher gewesen, aber das hast ja schon verneint.

**Comment by totocotonio** [comment]
IOB neu gestartet.

Funktioniert wieder.

Trotzdem Danke für die Unterstützung
