### ISSUE TITLE
Java-Script Fehler JS-Adapter 6.1.4

### ISSUE THREAD

**Issue by MecMax** [Pittini/iobroker-Batterienauswertung#39]
Hallo! Ich habe Dein Script 1.8.5 geladen und bekomme folgende Fehler:
![272](https://user-images.githubusercontent.com/80885820/209212560-88f8a6dd-2be6-4795-9223-14a7f316fac0.JPG)
![300](https://user-images.githubusercontent.com/80885820/209212698-299792d8-00d2-497b-a2f9-70d544f959c6.JPG)
![453](https://user-images.githubusercontent.com/80885820/209212980-73b4a3f6-e6ef-4891-8c6a-f874d6d2095b.JPG)
![471](https://user-images.githubusercontent.com/80885820/209213134-f6556144-a8c3-45fc-a5a5-9ba182ded30b.JPG)

Habe ich etwas vergessen? Oder passen die Java-Versionen nicht? Oder ist das einfach zu alt?

Script läuft auf foldende Fehler:
![Ablauffehler](https://user-images.githubusercontent.com/80885820/209213387-3f1d4308-290d-483e-a3dd-01e83726a073.JPG)

Viele Grüße
MecMax

**Comment by Pittini** [comment]
Skript is weder zu alt noch läufts ausm anderen Grund nicht. Haben zig Leute im Einsatz. Wennst Fehler kriegst, hast vermutlich was falsch gemacht, die Anleitung ist ausführlich, einfach alles mal kontrollieren oder nochmal neu machen. Das JS im Skript Sachen rot anmault kannste ignorieren.

**Comment by MecMax** [comment]
Hallo! Vielen Dank für Deine schnelle Antwort. Hatte Sorgen, dass das grundsätzlich nicht mehr funktioniert. Dann schmeiß ich mich jetzt Mal wieder rein ins Getümmel!
MfG mecmax
