### ISSUE TITLE
Werte für Alexa speichern

### ISSUE THREAD

**Issue by Siggi0904** [Pittini/iobroker-Batterienauswertung#4]
Hallo,

ich verwende seit heute das Skript und hab dazu ein paar Fragen.

1. Muss man auf das Script noch ein Cron legen, oder läuft es selbst regelmäßig ab?
2. Können als Funktionserweiterung die aktuellen Stände, der guten und schlechten Sensoren in separate Variablen übergeben werden? Ich würde gern das Ergebnis in anderen Blockly weiterverwenden.
3. Kann die Alexa Ausgabe erweitert werden, dass auf den angesprochenem Gerät geantwortet wird?

Großen Dank im Voraus.

**Comment by Pittini** [comment]
> 1. Muss man auf das Script noch ein Cron legen, oder läuft es selbst regelmäßig ab?
Skript wird über Trigger größtenteils gesteuert und minütlich zusätzlich auf "tote" Geräte überprüft. Also nein, Du brauchst kein Cron etc.

> 2. Können als Funktionserweiterung die aktuellen Stände, der guten und schlechten Sensoren in separate Variablen übergeben werden? Ich würde gern das Ergebnis in anderen Blockly weiterverwenden.

Kannste das bitte etwas konkreter ausführen, machbar ist grundsätzlich mal alles.

> 3. Kann die Alexa Ausgabe erweitert werden, dass auf den angesprochenem Gerät geantwortet wird?

Keine Ahnung, da ich die Abhörwanze nicht nutze.

**Comment by Siggi0904** [comment]
Zu 1: Großen Dank, hatte schon Sorgen, dass es nicht läuft.
Zu 2: Ich hätte gern Variablen mit den Ergebnissen, ähnlich der html Variable für die Vis.
         Jeweils geteilt nach alles Okay, Warnung und ausgefallen, ggf. mit den Spannungen jeweils dazu.
         Oder die Spannungen in einer separaen Variable in gleicher Reihenfolge.
         Da ich mit Blockly erst beginne, weiß ich nicht, was da möglich ist.
Zu 3: Falls 2. super erstellt wird, würde 3 entfallen oder nur noch für Ausfallsmeldungen
         Ansonsten sollten dies auch Variablen sein, die man über Blockly ansteuern kann.
         Also z.B. DeviceID, Laustärke,SSML oder Speak der anzusteuernden Alexa.

Das Script hat viel Potential,um auch die Ausgaben an Alexa cool umzusetzen.

Großen Dank.

**Comment by Pittini** [comment]
Zu 2: Mal sehen ob ich mal dazukomm, aktuell eher nicht.
Zu 3: Wirds (von mir) nicht geben, da ich wie gesagt keine Alexa nutze, es somit weder testen könnte, noch weis ws da wie wo eingestellt werden kann. Kann gern jemand forken, integrieren und nen PR machen.

**Comment by Siggi0904** [comment]
Dank dir, falls zu 2 umgesetzt wird.
Zu 3 kann ich mit Blockly lösen.

**Comment by Pittini** [comment]
Sollten jetz mit 1.8.0 genug Datenpunkte vorhanden sein. Wenn Dir noch was fehlt kannst ja wieder aufmachen.
