### ISSUE TITLE
Optimierung Deconz-Geräte in Tabelle

### ISSUE THREAD

**Issue by Siggi0904** [Pittini/iobroker-Batterienauswertung#5]
Hallo,
wäre es möglich, dass das Script die Deconz-Geräte besser anzeigt?
Also, dass Name und und ID nicht vom root des Gerätes gezogen werden, sondern vom Datenpunkt direkt?

Aktuell sieht die Tabelle so aus:
![grafik](https://user-images.githubusercontent.com/4992106/99152912-2b216400-26a5-11eb-923e-02bdfd8c6030.png)

Ein Datenpunkt eines Deconz Sensors (hier Aqara Bewegungsmelder und Türkontakt) sieht so aus:
![grafik](https://user-images.githubusercontent.com/4992106/99152968-98cd9000-26a5-11eb-8cd7-b5d32ad5bb29.png)

Ich verwende die aktuelle Version 1.6.7

**Comment by Pittini** [comment]
Das Problem an der Sache ist, dass offenbar je nach User und Deconz Version das ganze sehr unterschiedlich benamt ist. Dass das in die root geht war auch schon ein Extrawunsch ausm Forum weil diesem User die verherige Variante nicht getaugt hat. Gleiche Begründung wie bei Dir, nurn anderer Level. 
Aber was Du machen kannst, is nach Zeile 404 das hier einzufügen:
`    if (Id.indexOf("deconz.") > -1) parentDevicelId = Id;`
Sollte klappen, aber mußt nach updates wiederholen weils dann wieder weg ist. Ich werd mal überlegen das als Option zu machen. Gib bitte Feedback obs geklappt hat.

**Comment by Siggi0904** [comment]
Jo, so sieht das schon besser aus.
![grafik](https://user-images.githubusercontent.com/4992106/99154252-a1769400-26ae-11eb-9f45-db69187435f8.png)

Also Option wäre das gut,könnte ja auch bei anderen Geräteherstellern vorkommen.

Wäre es denn möglich das Script in einen Adapter zu überführen?
Dann könntest du den Aufbau so machen, wie z.B. bei der Heizungssteuerung
und auch freie Namen für die Geräte verwenden.

**Comment by Pittini** [comment]
> Also Option wäre das gut,könnte ja auch bei anderen Geräteherstellern vorkommen.

Ja, wird vermutl. im nächsten update drin sein.
 
> Wäre es denn möglich das Script in einen Adapter zu überführen?
Das ist bestimmt möglich.....wenn mans kann....ich kanns ned.

**Comment by Pittini** [comment]
fixed with 1.7.0
