### ISSUE TITLE
Log wird vollgeschrieben

### ISSUE THREAD

**Issue by Siggi0904** [Pittini/iobroker-Batterienauswertung#7]
Hallo,

mein log bekommt extrem viele Einträge von dem Script.
Ich nutze die aktuelle Versio 1.7.0

Also die Version von Freitag oder so.

![Screenshot 2021-01-11 192112](https://user-images.githubusercontent.com/4992106/104222371-799f7480-5442-11eb-93ed-e7923d9d0abc.jpg)

**Comment by Pittini** [comment]
Ziehs Dir bitte nochmal ich hatte da noch was geändert aber keine neue Version gemacht, sollte weg sein.

**Comment by Siggi0904** [comment]
Läuft seit ca. 10 Minuten, sieht gut aus.
