### ISSUE TITLE
Problem mit Prozentwerten

### ISSUE THREAD

**Issue by str3000** [Pittini/iobroker-Batterienauswertung#9]
Hallo,
vielen Dank für das tolle Skript.
Ich habe aktuell ein Problem mit Ikea Tastern die nur Prozentwerte 0 .. 100 % liefert.
Dafür habe ich angelegt:  "BatterieSpannung_1000"
Grenze habe ich aktuell auf "33" eingestellt.
Bei drei Geräten habe ich Werte:
76 %
21 %
34%
In der Tabelle wird 76 richtig angezeigt, die anderen Werte sind vertauscht anscheinend mit %live und Uist stimmt somit nicht. Auswertung auch nicht. Einer sollte kritisch sein.
Bei den falsche ist der Datentyp Zahl mit Einheit %. Bei 76% ist Datentyp String.

![grafik](https://user-images.githubusercontent.com/48569357/107127052-cf393680-68b3-11eb-97b7-1b9c3cf9bb92.png)

Mache ich was falsch?

**Comment by Pittini** [comment]
> Ich habe aktuell ein Problem mit Ikea Tastern die nur Prozentwerte 0 .. 100 % liefert.
> Dafür habe ich angelegt: "BatterieSpannung_1000"
> Grenze habe ich aktuell auf "33" eingestellt.

Wie kommst Du auf BatterieSpannung_1000? Das ist völlig sinnfrei und würde ne 100 Volt Batterie bedeuten, was das Skript ja auch so anzeigt. Was ist denn so schwer dran zu verstehen, dass da die NENNSPANNUNG der Batterie oder des Gerätes anzugeben ist? Ob das lowbat oder % oder ne Spannung ist, entscheidet das Skript selbsständig anhand der Unit bzw. des Datentyps. Damit sollte die % Thematik klar sein. Zum Thema Datenpunkt String, wenn da ne Zahl als String ankommt ist das halt schlichtweg falsch und deswegen wird das Skript das auch nicht verarbeiten. Aber da kann das Skript nix dafür, sondern der Adapter oder was auch immer das bereitstellt.

**Comment by str3000** [comment]
Hallo Pittini,
danke für die schnelle Antwort.
Du hast recht ich interpretiere viel und bin nun an dem Punkt wo ich nicht mehr weiterkomme.
Zur Erklärung:
Bei den meisten Zigbegeräten die ich habe kommt mV als Einheit.
Das Skript funkioniert dann nur, wenn ich bei 3200mV die BatterieSpannung_3200 verwende.
Die Einheit zeigt es dann eben falsch an. Kann ich damit leben.
Anders habe ich das nicht hinbekommen.
Wenn ich eine Range von 0 .. 100 überwache habe ich eben 1000 eingetragen.
Soweit tut das. 
Bei dem Datentyp hast du nicht richtig gelesen.
Dort wo das Problem herrscht, ist der Datentyp "Zahl" definiert und sollt somit nicht das Problem sein.

Was soll ich den verwenden wenn eine Prozentzahl von 0 ..100 % verwendet wird?
In der Anleitung habe ich nichts gefunden.

Gruß
str3000

**Comment by Pittini** [comment]
Zeig mir mal nen Screenshot oder den TExt vom Raw des betreffenden DAtenpuntes der falsch ist. Und die Sache mit den mV, was ist das denn fürn Käse, davon hör ich zum ersten mal. Aber gut wenns das gibt, kann ich mal überlegen ob ich das abfragen kann, weil so ist das von hinten durch die Brust ins Auge. Für % verwendest Du ganz normal die Nennspannung. Die Unit muß % und der Wert ne Zahl sein, dann erkennt das Skript das selbsständig.
Zum Thema Warngrenze wieso hast Du ein Problem mit 0%, wo Du doch selber festlegst wo die 0% Spannungsmäßig sind. Und zusätzlich kriegste ja auch noch die aktuell leerste Batterie angezeigt, seh da keine notwendigkeit für ne zusätzliche Warngrenze.

**Comment by str3000** [comment]
Ich weis grade nicht ob es wirklich verkehrt ist oder ich nur was anderes erwartet habe.
Das unterschiedliche Verhalten von dem Nuki und den beiden Ikea hat mich das so vermuten lassen.

Zu der Warngrenze:
Also bei 0 % funktioniert das Gerät nicht mehr. Ich möchte natürlich vorher eine Warnung das ich demnächst die Batterie tauschen muss. Dann sende ich mir eine Nachricht zu. 
Wäre doof wenn ich vor der Haustür stehe und der Türöffner geht nicht mehr.
Übrigens kommen alle Werte von Zigbee2mqtt als mV. Sind so ca. 70 Sensoren bei mir.
Ich glaube alle Geräte liefern die 0..100% Werte. Das könnte ich also noch umstellen.
Nicht alle liefern jedoch die Spannung.

Hier ein RAW Wert eines Ikea-Wertes (das habe ich in der Hand wie es aussieht): 
```
{
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1612634580219,
  "common": {
    "name": "Ikea Dimmer Licht  Cora",
    "type": "number",
    "role": "value.battery",
    "unit": "%",
    "read": true,
    "write": true
  },
  "native": {
    "type": "number",
    "role": "value.battery",
    "name": "Ikea Dimmer Licht  Cora",
    "unit": "%",
    "read": true,
    "write": true
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "javascript.0.mqtt.0x90fd9ffffe1895ff.battery",
  "type": "state"
}
```

Hier ein RAW Wert des Nuki-Wertes (das kommt von der Instanz direkt):
```
{
  "from": "system.adapter.nuki-extended.0",
  "user": "system.user.admin",
  "ts": 1603376007443,
  "common": {
    "name": "(no description given)",
    "role": "state",
    "type": "string",
    "write": false,
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": 0,
        "maxLength": 10,
        "retention": "63072000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "nuki-extended.0.smartlocks.haustüre.state.batteryCharge",
  "type": "state"
}
```

**Comment by Pittini** [comment]
Du hasts immer noch nicht verstanden. DU legst die 0% fest, DAS ist Deine Warngrenze. Wenns wirklich nimmer funktioniert wirds ja als dead gemeldet. Es sind also genug Indikatoren vorhanden.
Der Nuki Datenpunkt ist, wenn da letztendlich ne Zahl drinsteht, schlichtweg falsch, da mußte nen Issue beim Nuki Adapter machen. Die Ikea Datenpunkte sind ok.

**Comment by str3000** [comment]
ok. Ich habe es verstanden. Besten dank für Deine Unterstützung.
